receivers:
  otlp:
    protocols:
      http:

processors:
  batch:

exporters:
  zipkin:
    endpoint: http://tempo:9411

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [zipkin]
